const Events = {
    AccountAddSubmit: 'accountAddSubmit',
    ChangePath: 'changePath',
    ExtractFromIPFSSubmit: 'extractFromIPFSSubmit',
    ExtractFromStorageSubmit: 'extractFromStorageSubmit',
    FormRendered: 'formRendered',
    GoToUploadToIPFSBlock: 'goToUploadToIPFSBlock',
    InputAddress: 'inputAddress',
    InputDelta: 'inputDelta',
    InputHash: 'inputHash',
    InputRole: 'inputRole',
    RefreshPage: 'refreshPage',
    RootAddition: 'rootAddition',
    ZoneAddition: 'zoneAddition',
    RouteAddition: 'routeAddition',
    ZoneAdditionSubmit: 'zoneAdditionSubmit',
    RootAdditionSubmit: 'rootAdditionSubmit',
    RouteAdditionSubmit: 'routeAdditionSubmit',
    RootRequest: 'rootRequest',
    RootShow: 'rootShow',
    RootAdditionMode: 'rootAdditionMode',
    ZoneAdditionMode: 'zoneAdditionMode',
    RegisterPilotSubmit: 'registerPilotSubmit',
    UploadImage: 'uploadImage',
    UploadToIPFS: 'uploadToIPFS',
    UploadToIPFSSubmit: 'uploadToIPFSSubmit',
    SelectMapOption: 'selectMapOption',
};

export default Events;
